name = "Swirl"
uuid = "8c8c1a2e-4f5b-4c3d-9e2f-1a2b3c4d5e6f"
authors = ["Swirl.jl Contributors"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
ReplMaker = "0.2.7"
julia = "1.6"
